service: serverless
provider:
  name: aws
  runtime: nodejs12.x
  profile: ramirentuser
  region: us-east-1
  timeout: 30
  environment: ${file(../envs/dev.json)}

plugins:
  - serverless-sequelize-migrations

functions:
  SaveFile:
    handler: handler.saveFile
    events:
      - s3:
          bucket: sourcebucket105
          event: s3:ObjectCreated:*

